from __future__ import annotations

from collections.abc import Mapping

from .Event import Event, ExternalEvent, GameEvent, ProjectedEvent, QuestEvent, StatusEvent


GAME_EVENT_CATEGORIES: dict[str, tuple[str, ...]] = {
    "System": (
        "LoadGame",
        "Shutdown",
        "NewCommander",
    ),
    "Combat": (
        "Died",
        "Resurrect",
        "InDanger",
        "OutOfDanger",
        "CombatEntered",
        "CombatExited",
        "LegalStateChanged",
        "CommitCrime",
        "Bounty",
        "CapShipBond",
        "Interdiction",
        "Interdicted",
        "BeingInterdicted",
        "EscapeInterdiction",
        "FactionKillBond",
        "FighterDestroyed",
        "HeatDamage",
        "HeatWarning",
        "HullDamage",
        "PVPKill",
        "ShieldState",
        "ShipTargeted",
        "BountyScanned",
        "UnderAttack",
        "CockpitBreached",
        "CrimeVictim",
        "SystemsShutdown",
        "SelfDestruct",
    ),
    "Trading": (
        "BuyTradeData",
        "CollectCargo",
        "EjectCargo",
        "MarketBuy",
        "MarketSell",
        "CargoTransfer",
        "Market",
    ),
    "Mining": (
        "AsteroidCracked",
        "MiningRefined",
        "ProspectedAsteroid",
        "LaunchDrone",
        "RememberLimpets",
    ),
    "Ship Updates": (
        "FSDJump",
        "FSDTarget",
        "StartJump",
        "FsdCharging",
        "SupercruiseEntry",
        "SupercruiseExit",
        "ApproachSettlement",
        "InDockingRange",
        "GlideModeExited",
        "GlideModeEntered",
        "Docked",
        "Undocked",
        "DockingCanceled",
        "DockingDenied",
        "DockingGranted",
        "DockingRequested",
        "DockingTimeout",
        "DockingComputerDocking",
        "DockingComputerUndocking",
        "DockingComputerDeactivated",
        "NavRoute",
        "NavRouteClear",
        "CrewLaunchFighter",
        "VehicleSwitch",
        "LaunchFighter",
        "DockFighter",
        "FighterRebuilt",
        "FuelScoop",
        "RebootRepair",
        "RepairDrone",
        "AfmuRepairs",
        "ModuleInfo",
        "Synthesis",
        "JetConeBoost",
        "JetConeDamage",
        "LandingGearUp",
        "LandingGearDown",
        "HudSwitchedToAnalysisMode",
        "HudSwitchedToCombatMode",
        "FlightAssistOn",
        "FlightAssistOff",
        "HardpointsRetracted",
        "HardpointsDeployed",
        "LightsOff",
        "LightsOn",
        "CargoScoopRetracted",
        "CargoScoopDeployed",
        "SilentRunningOff",
        "SilentRunningOn",
        "FuelScoopStarted",
        "FuelScoopEnded",
        "FsdMassLockEscaped",
        "FsdMassLocked",
        "LowFuelWarningCleared",
        "LowFuelWarning",
        "HighGravityWarning",
        "NightVisionOff",
        "NightVisionOn",
        "SupercruiseDestinationDrop",
    ),
    "SRV Updates": (
        "LaunchSRV",
        "DockSRV",
        "SRVDestroyed",
        "SrvHandbrakeOff",
        "SrvHandbrakeOn",
        "SrvTurretViewConnected",
        "SrvTurretViewDisconnected",
        "SrvDriveAssistOff",
        "SrvDriveAssistOn",
    ),
    "On-Foot Updates": (
        "Disembark",
        "Embark",
        "BookDropship",
        "BookTaxi",
        "CancelDropship",
        "CancelTaxi",
        "CollectItems",
        "DropItems",
        "BackpackChange",
        "BuyMicroResources",
        "SellMicroResources",
        "TransferMicroResources",
        "TradeMicroResources",
        "BuySuit",
        "BuyWeapon",
        "SellWeapon",
        "UpgradeSuit",
        "UpgradeWeapon",
        "CreateSuitLoadout",
        "DeleteSuitLoadout",
        "RenameSuitLoadout",
        "SwitchSuitLoadout",
        "WeaponSelected",
        "UseConsumable",
        "FCMaterials",
        "ScanOrganic",
        "SellOrganicData",
        "LowOxygenWarningCleared",
        "LowOxygenWarning",
        "LowHealthWarningCleared",
        "LowHealthWarning",
        "BreathableAtmosphereExited",
        "BreathableAtmosphereEntered",
        "DropShipDeploy",
    ),
    "Stations": (
        "StationServices",
        "ShipyardBuy",
        "ShipyardNew",
        "ShipyardSell",
        "ShipyardTransfer",
        "ShipyardSwap",
        "StoredShips",
        "ModuleBuy",
        "ModuleRetrieve",
        "ModuleSell",
        "ModuleSellRemote",
        "ModuleStore",
        "ModuleSwap",
        "LoadoutEquipModule",
        "LoadoutRemoveModule",
        "Outfitting",
        "BuyAmmo",
        "BuyDrones",
        "RefuelAll",
        "RefuelPartial",
        "Repair",
        "RepairAll",
        "RestockVehicle",
        "FetchRemoteModule",
        "MassModuleStore",
        "ClearImpound",
        "CargoDepot",
        "CommunityGoal",
        "CommunityGoalDiscard",
        "CommunityGoalJoin",
        "CommunityGoalReward",
        "EngineerContribution",
        "EngineerCraft",
        "EngineerLegacyConvert",
        "MaterialTrade",
        "TechnologyBroker",
        "PayBounties",
        "PayFines",
        "PayLegacyFines",
        "RedeemVoucher",
        "ScientificResearch",
        "Shipyard",
        "CarrierJump",
        "CarrierBuy",
        "CarrierStats",
        "CarrierJumpRequest",
        "CarrierDecommission",
        "CarrierCancelDecommission",
        "CarrierBankTransfer",
        "CarrierDepositFuel",
        "CarrierCrewServices",
        "CarrierFinance",
        "CarrierShipPack",
        "CarrierModulePack",
        "CarrierTradeOrder",
        "CarrierDockingPermission",
        "CarrierNameChanged",
        "CarrierJumpCancelled",
        "ColonisationConstructionDepot",
        "FetchRemoteModuleCompleted",
        "ShipyardTransferCompleted",
        "CarrierJumpWarning",
        "CarrierJumpArrived",
        "CarrierJumpCooldownComplete",
    ),
    "Social": (
        "Idle",
        "CrewAssign",
        "CrewFire",
        "CrewHire",
        "ChangeCrewRole",
        "CrewMemberJoins",
        "CrewMemberQuits",
        "CrewMemberRoleChange",
        "EndCrewSession",
        "JoinACrew",
        "KickCrewMember",
        "QuitACrew",
        "NpcCrewRank",
        "Promotion",
        "Friends",
        "WingAdd",
        "WingInvite",
        "WingJoin",
        "WingLeave",
        "SendText",
        "ReceiveText",
        "AppliedToSquadron",
        "DisbandedSquadron",
        "InvitedToSquadron",
        "JoinedSquadron",
        "KickedFromSquadron",
        "LeftSquadron",
        "SharedBookmarkToSquadron",
        "SquadronCreated",
        "SquadronDemotion",
        "SquadronPromotion",
        "WonATrophyForSquadron",
        "PowerplayCollect",
        "PowerplayDefect",
        "PowerplayDeliver",
        "PowerplayFastTrack",
        "PowerplayJoin",
        "PowerplayLeave",
        "PowerplaySalary",
        "PowerplayVote",
        "PowerplayVoucher",
    ),
    "Exploration": (
        "CodexEntry",
        "DiscoveryScan",
        "Scan",
        "FSSAllBodiesFound",
        "FSSBodySignals",
        "FSSBiologicalSignals",
        "FSSDiscoveryScan",
        "FirstPlayerSystemDiscovered",
        "FleetCarrierDiscovered",
        "ResourceExtractionDiscovered",
        "InstallationDiscovered",
        "NavBeaconDiscovered",
        "TouristBeaconDiscovered",
        "MegashipDiscovered",
        "GenericDiscovered",
        "OutpostDiscovered",
        "CombatDiscovered",
        "StationDiscovered",
        "UnknownSignalDiscovered",
        "MaterialCollected",
        "MaterialDiscarded",
        "MaterialDiscovered",
        "MultiSellExplorationData",
        "NavBeaconScan",
        "BuyExplorationData",
        "SAAScanComplete",
        "SAASignalsFound",
        "ScanBaryCentre",
        "SellExplorationData",
        "Screenshot",
        "ApproachBody",
        "LeaveBody",
        "Liftoff",
        "Touchdown",
        "DatalinkScan",
        "DatalinkVoucher",
        "DataScanned",
        "Scanned",
        "USSDrop",
        "NoScoopableStars",
        "HGECandidateFound",
        "HighValueLandmarksBody",
    ),
    "Missions & Quests": (
        "QuestEvent",
        "MissionAbandoned",
        "MissionAccepted",
        "MissionCompleted",
        "MissionFailed",
        "MissionRedirected",
    ),
}


EVENT_CATEGORY_BY_NAME: dict[str, str] = {
    event_name.lower(): category
    for category, event_names in GAME_EVENT_CATEGORIES.items()
    for event_name in event_names
}


def event_name_to_category(event_name: str | None) -> str | None:
    if not event_name:
        return None
    return EVENT_CATEGORY_BY_NAME.get(event_name.lower())


def event_category(event: Event) -> str | None:
    event_name: object | None = None
    if isinstance(event, (GameEvent, ProjectedEvent, ExternalEvent, QuestEvent)):
        event_name = event.content.get("event")
    elif isinstance(event, StatusEvent):
        event_name = event.status.get("event")
    if isinstance(event_name, str):
        return event_name_to_category(event_name)
    return None


def categories_for_events(events: list[Event]) -> dict[str, list[Event]]:
    categories: dict[str, list[Event]] = {}
    for event in events:
        category = event_category(event)
        if category:
            categories.setdefault(category, []).append(event)
    return categories


def get_event_categories() -> Mapping[str, tuple[str, ...]]:
    return GAME_EVENT_CATEGORIES
